version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase...
      - apt-get update -y && apt-get install -y make apt-transport-https
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entered pre_build phase...
      - cd ./react npm install
      - aws s3 cp $ENV_BUCKET/.env ./react/.env
  build:
    commands:
      - cd react/
      - npm run build
      - echo "React build completed..."
  post_build:
    commands:
      - aws s3 sync ./react/dist $STORAGE_BUCKET --delete
      - echo Successfully uploaded build to S3
  